In [1]:
#!pip3 install snscrape

In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

In [3]:
# Creating list to append tweet data to
tweets_list1 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('the Art of War since:2022-06-01 until:2023-01-01').get_items()):
    if i>1000:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('The song of Achille since:2022-06-01 until:2023-01-01').get_items()):
    if i>1000:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('Batman : the Dark Night Return since:2022-06-01 until:2023-01-01').get_items()):
    if i>1000:
        break    
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('The Picture of Dorian Gray since:2022-06-01 until:2023-01-01').get_items()):
    if i>1000:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('The Book Thief since:2022-06-01 until:2023-01-01').get_items()):
    if i>1000:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
# Creating a dataframe from the tweets list above 
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [4]:
#nettoyage des données (utilisation de la librairie regex)
tweets_df1['Text'] = tweets_df1['Text'].str.replace(r"[^a-zA-Z0-9]", " ")
tweets_df1['Text'] = tweets_df1['Text'].str.replace("https", "").str.replace("t co", "")
tweets_df1

C:\Users\Administrateur\AppData\Local\Temp\ipykernel_15904\3003598582.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  tweets_df1['Text'] = tweets_df1['Text'].str.replace(r"[^a-zA-Z0-9]", " ")

,Datetime,Tweet Id,Text,Username
0,2022-12-31 23:58:04+00:00,1609338127956545536,The Ultimate Art of War A Step by Step Illust...,mosciski52ejffd
1,2022-12-31 23:50:55+00:00,1609336328784576513,truckdriverpleb Unfortunately that is a fact ...,PeterRMacIsaac
2,2022-12-31 23:49:26+00:00,1609335954514366464,lexfridman I read most of those and would rec...,levosaurus
3,2022-12-31 23:48:15+00:00,1609335659277291523,lexfridman The art of war is going to change ...,BullstreetLLC
4,2022-12-31 23:47:13+00:00,1609335398509195268,coupusa EndWokeness The problem with that wh...,GigaChadwick
...,...,...,...,...
3136,2022-12-14 03:35:23+00:00,1602869837004349443,Do you struggle picking out what to read next ...,nemo_nista
3137,2022-12-14 03:11:12+00:00,1602863750653935617,At this weekend I plan to watch Crime Action ...,bingbingliucdc1
3138,2022-12-14 03:06:28+00:00,1602862560570920960,she is ghariba Quran The book thief Tuesdays ...,__dontaskwhy__x
3139,2022-12-14 02:00:54+00:00,1602846057746104324,r4hema six of crows the bell jar the book t...,c13ment1ne
3140,2022-12-14 01:51:16+00:00,1602843633798942720,At this weekend I plan to watch Classic Sci F...,bingbingliucdc1

In [5]:
# transformation du dataframe en CSV
tweets_df1.to_csv('csv/tweets.csv', index=False)